### ISSUE TITLE
Transparent background not working as OBS Studio BrowserSource

### ISSUE THREAD

**Issue by Lewdicolo** [Nifty255/Bit-Boss-Battles#14]
I have the transparent background option turned on but the browsersource has a black background. Even when I enable "Chroma (Blue) Background" it doesn't update the background to blue. It used to work, but stopped yesterday

**Comment by Nifty255** [comment]
Try recreating the browser source. Usually a new browser source will
include some default CSS code that may be missing. BBB isn't supposed to
need it, but it might be a workaround until I can fix the issue.

**Comment by Lewdicolo** [comment]
That was one of the first things I tried, but it still has the black background and won't update with the changes I make in the settings tab

**Comment by Lewdicolo** [comment]
I figured it out. Had to revoke permissions on Twitch's end and reconnect. Thanks for the awesome tool!

**Comment by Nifty255** [comment]
As I am currently working, I won't be able to address the issue for another
8 hours, but I can ask for some information:

1. Have you copied the new link format since yesterday's update?
2. Have you tried disabling and re-enabling Persistence?
3. Have you tried reauthorizing and re-copying the link?
4. Copy the link into your preferred browser. Is the background still
black, or is it white (transparent in ordinary browsers will appear white)?
5. Is it actually black, or is it a really dark gray?

**Comment by Nifty255** [comment]
Glad to hear! Is it also remembering settings now?

**Comment by Lewdicolo** [comment]
Yes it is remembering the settings now. Working as intended. I'll also answer your questions just so you know what was happening:

1. I was using the new link
2. Didn't try disabling or re-enabling Persistence
3. Reauthorizing it on your site didn't fix it, but reauthorizing it on Twitch's end did.
4. When I launched the widget in it's own Chrome window, it had the dark gray background.
5. It was the really dark gray.

Thanks for your time!
